# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20170321_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodSkillTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_goodskilltag_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearningSkillTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_learningskilltag_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_handle', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='profile',
            name='good_skills',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='users.GoodSkillTag', to='users.SkillTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='profile',
            name='learning_skills',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='users.LearningSkillTag', to='users.SkillTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningskilltag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_skill_tag', to='users.SkillTag'),
        ),
        migrations.AddField(
            model_name='goodskilltag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_skill_tag', to='users.SkillTag'),
        ),
    ]
