# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170326_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='summary',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='good_skills',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='users.GoodSkillTag', to='users.SkillTag', verbose_name='My Good Skills'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='learning_skills',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='users.LearningSkillTag', to='users.SkillTag', verbose_name="Skills I'm still learning"),
        ),
    ]
