# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170326_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code_url',
            field=models.URLField(blank=True, verbose_name='Code URL (eg. GitHub)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Eg. Website, Twitter, portfolio'),
        ),
    ]
