# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170326_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='modified',
            new_name='updated',
        ),
    ]
