# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 22:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spam', models.BooleanField(default=False)),
                ('answer', models.BooleanField(default=False)),
                ('body', models.TextField(max_length=500, null=True, verbose_name='Response')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date added')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='body_md',
            field=models.TextField(blank=True, verbose_name='Question body (Markdown)'),
        ),
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
