# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20170321_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='body',
        ),
        migrations.AddField(
            model_name='response',
            name='body_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='response',
            name='body_md',
            field=models.TextField(blank=True, verbose_name='Response body (Markdown)'),
        ),
        migrations.AddField(
            model_name='response',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
