# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 22:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_auto_20170321_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date added')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Response')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
