# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20170505_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='date_added',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='last_modified',
            new_name='updated',
        ),
    ]
